engines:
  fixme:
    enabled: true
  rubocop:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby

ratings:
  paths:
  - "**.rb"

exclude_paths:
  - spec/**/*
